feat: implement initial structure for explore.distributed.press
hyphacoop/explore.distributed.press pull request #1
Opened 2024-12-13 16:50 UTC by akhileshthite

2025-01-06 22:04 UTC, RangerMauve requested changes
Good start! Got a few questions around URLs though. Also we're gonna change the site list endpoint soon to return the full public data rather than just domains

2025-01-06 22:04 UTC, RangerMauve commented on src/p2pLinks.js
> +  const hyperUrl = `https://${domain}/.well-known/hyper`;
Are these defined by a spec somewhere? I'm not sure where this is coming from

2025-01-06 22:04 UTC, RangerMauve commented on src/p2pLinks.js
> +async function loadFetch() {
Instead lets just use globalThis.fetch, it's available in node 20+ already

2025-01-06 22:04 UTC, RangerMauve commented on src/scraper.js
> +async function loadFetch() {
Lets use the built in fetch here

2025-01-06 22:04 UTC, RangerMauve commented on src/index.js
> +main().catch((err) => console.error('Error in main function:', err.message));
Lets use `type: module` in the package.json and use top level await so we can get rid of this `main()` wrapper

2025-01-06 22:04 UTC, RangerMauve commented on src/generator.js
> +        <title>Distributed Press Site Index</title>
Lets add a description meta tag too

2025-01-06 22:04 UTC, RangerMauve commented on src/index.js
> +      return manualSites.filter((site) => site.public);
Lets just assume all the manual sites are public so we can avoid accidentally hiding them

2025-01-06 22:04 UTC, RangerMauve commented on src/fetchSites.js
> +      const response = await fetch(`${instance}/.well-known/distributed.press/sites`);
Where is this URL coming from, is it necessary?

2025-01-06 22:04 UTC, RangerMauve commented on .github/workflows/deploy-distributed-press.yaml
> +        run: node ./src/index.js
```suggestion
        run: node ./
```

Add a `main` field in the package.json

2025-01-06 22:04 UTC, RangerMauve commented on .github/workflows/deploy-distributed-press.yaml
> +          node-version: 18
```suggestion
          node-version: 22
```

22 is the latest LTS version so we should be using that

2025-01-16 19:04 UTC, akhileshthite commented on src/fetchSites.js
> +      const response = await fetch(`${instance}/.well-known/distributed.press/sites`);
The `.well-known/distributed.press/sites` follows the `.well-known` pattern from [RFC 8615](https://datatracker.ietf.org/doc/html/rfc8615) and aligns with Distributed Press's use of `.well-known`, as seen in [nginx-static.j2](https://github.com/hyphacoop/api.distributed.press/blob/8958235679e35e812a76c467c858869dbc67bfdd/ansible/roles/distributed_press/templates/nginx-static.j2#L23) (e.g., webfinger, host-meta), not explicitly defined there, it extends the .well-known namespace for metadata and discovery, consistent with Distributed Press conventions.

I think this https://github.com/hyphacoop/api.distributed.press/pull/100 will eliminate the need to fetch .well-known endpoints or scrape site metadata. Once merged, I'll update the code to leverage this new API response.

2025-01-16 19:05 UTC, akhileshthite commented
We should remove these sites:

https://dp.akhilesh.art/
https://akhileshthite.github.io/
https://try.distributed.press/

2025-01-16 19:06 UTC, akhileshthite commented on src/p2pLinks.js
> +  const hyperUrl = `https://${domain}/.well-known/hyper`;
I think this https://github.com/hyphacoop/api.distributed.press/pull/100 will eliminate the need to fetch .well-known endpoints or scrape site metadata. Once merged, I'll update the code to leverage this new API response.

2025-01-21 14:53 UTC, RangerMauve commented on src/fetchSites.js
> +      const response = await fetch(`${instance}/.well-known/distributed.press/sites`);
Lets skip this feature and stick to the p2p URLs in the site list

2025-01-22 20:53 UTC, RangerMauve requested changes
One last issue and then we can merge

2025-01-22 20:53 UTC, RangerMauve commented on src/fetchSites.js
> +const API_ENDPOINT = `${knownInstances}/sites`
Known instances is a list, when fetching we should iterate the list and concat the results. This currently turns the list into a string which will break when we have more than one instance.

2025-01-23 17:16 UTC, RangerMauve approved these changes

2025-01-23 17:16 UTC, merged